from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
driver=webdriver.Chrome("C:\\Users\\Anju Anil\\Desktop\\python\\chromedriver")
driver.get("https://www.dummyticket.com/dummy-ticket-for-visa-application/")

driver.maximize_window()
driver.find_element_by_id("product_551").click()
driver.find_element(by=By.NAME,value="travname").send_keys("Anusree")
driver.find_element(by=By.NAME,value="travlastname").send_keys("Nikhil")
driver.find_element_by_name("order_comments").send_keys("Eco-friendly, Provide Good and Sincere Employees")
#driver.find_element_by_id("dob").send_keys("26-04-1995")
driver.find_element(by=By.ID,value='sex_2').click()
driver.find_element_by_name("addmorepax").click()
dropdown=driver.find_element(by=By.XPATH,value="//*[@id='addpaxno']")
dd=Select(dropdown)
#dd.select_by_visible_text("add 1 more passenger (100%)")
dd.select_by_index(0)
driver.find_element(by=By.ID, value="traveltype_1").click()
driver.find_element_by_name("fromcity").send_keys("Kozhikode")
driver.find_element_by_id("tocity").send_keys("Bangalore")
#Departure Date
driver.find_element_by_name("notes").send_keys("No other details")
dd2=driver.find_element_by_id("reasondummy")
selction=Select(dd2)
selction.select_by_index(3)
driver.find_element(by=By.CSS_SELECTOR, value="input.input-radio[id=deliverymethod_2]").click()
driver.find_element_by_id("billname").send_keys("Akbar Travels, Kozhikode")
driver.find_element_by_id("billing_phone").send_keys("3412345679")
driver.find_element_by_id("billing_email").send_keys("akbartravels@gmail.com")
dd3=driver.find_element_by_id("billing_country")
sel=Select(dd3)
sel.select_by_visible_text("India")
driver.find_element_by_name("billing_address_1").send_keys("Variyamkandi, Kommeri")
driver.find_element_by_name("billing_city").send_keys("Kozhikode")
dd4=driver.find_element_by_id("billing_state")
sel2=Select(dd4)
sel2.select_by_visible_text("Kerala")
driver.find_element_by_name("billing_postcode").send_keys("673007")
